# Generated by Django 5.1.7 on 2025-05-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
