# Generated by Django 5.1.7 on 2025-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0003_remove_auction_rating_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
